-- =============================================================================
-- Catálogo ERP Glazia — dimensões BI + enriquecimento de ctl_produtos / ctl_custos
-- Compatível com o contrato atual da API (linha, produto, cor, tipo_custo).
-- =============================================================================

-- —— Dimensões de referência (Power BI / star schema) ——

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_unidade (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('VENDA', 'CUSTO', 'AMBOS'))
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_linha (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  tipo_sistema text NOT NULL,
  -- ALUMINIO | VIDRO | ESTRUTURAL | ACM | AUTOMACAO | MADEIRA_HIBRIDO | INOX
  descricao text,
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_cor (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  familia_cor text NOT NULL,
  -- NEUTRO | METALICO | ESCURO | CLARO | COLORIDO | ESPECIAL
  aplicavel_a text NOT NULL DEFAULT 'AMBOS',
  -- PERFIL | VIDRO | AMBOS
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_familia_produto (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  segmento text NOT NULL,
  -- RESIDENCIAL | COMERCIAL | INDUSTRIAL | AMBOS
  descricao text,
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_categoria_produto (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  descricao text,
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_tipo_custo (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  grupo_bi text NOT NULL,
  -- MATERIAL | SERVICO | LOGISTICA | PERDA | APOIO
  descricao text,
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_espessura (
  codigo text PRIMARY KEY,
  mm numeric(6,2) NOT NULL,
  aplicavel_a text NOT NULL DEFAULT 'VIDRO',
  -- VIDRO | PERFIL | AMBOS
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_tipo_vidro (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  familia text NOT NULL,
  -- BASE | SEGURANCA | CONTROLE_SOLAR | DECORATIVO | ESPECIAL
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_marca (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'GENERICA',
  -- PERFIL | VIDRO | FERRAGEM | AUTOMACAO | GENERICA
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_acabamento (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  processo text,
  -- PINTURA | ANODIZACAO | POLIDO | FOSCO | NATURAL | LAMINADO
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dt_catalogo.dim_fornecedor (
  id_fornecedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'MATERIAL',
  -- MATERIAL | SERVICO | LOGISTICA | MISTO
  cidade text,
  uf char(2),
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS dim_fornecedor_nome_uk
  ON dt_catalogo.dim_fornecedor (lower(nome));

-- —— Enriquecimento das tabelas operacionais (não quebra API) ——

ALTER TABLE dt_catalogo.ctl_produtos
  ADD COLUMN IF NOT EXISTS familia text,
  ADD COLUMN IF NOT EXISTS marca text,
  ADD COLUMN IF NOT EXISTS acabamento text,
  ADD COLUMN IF NOT EXISTS segmento text,
  ADD COLUMN IF NOT EXISTS codigo_interno text;

ALTER TABLE dt_catalogo.ctl_custos
  ADD COLUMN IF NOT EXISTS marca text,
  ADD COLUMN IF NOT EXISTS subtipo text,
  ADD COLUMN IF NOT EXISTS acabamento text,
  ADD COLUMN IF NOT EXISTS codigo_interno text,
  ADD COLUMN IF NOT EXISTS origem text,
  ADD COLUMN IF NOT EXISTS id_fornecedor integer
    REFERENCES dt_catalogo.dim_fornecedor(id_fornecedor)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- Ajusta CHECK de vidro: permite tipo_vidro em tipos especiais de vidro
ALTER TABLE dt_catalogo.ctl_custos DROP CONSTRAINT IF EXISTS ctl_custos_vidro_chk;
ALTER TABLE dt_catalogo.ctl_custos
  ADD CONSTRAINT ctl_custos_vidro_chk CHECK (
    tipo_vidro IS NULL
    OR tipo_custo IN ('VIDRO', 'VIDRO_ESPECIAL')
  );

ALTER TABLE dt_catalogo.ctl_custos DROP CONSTRAINT IF EXISTS ctl_custos_origem_chk;
ALTER TABLE dt_catalogo.ctl_custos
  ADD CONSTRAINT ctl_custos_origem_chk CHECK (
    origem IS NULL OR origem IN ('COMPRA', 'SERVICO', 'INTERNO', 'TERCEIRO')
  );

CREATE INDEX IF NOT EXISTS ctl_produtos_familia_idx
  ON dt_catalogo.ctl_produtos (familia, categoria) WHERE ativo;
CREATE INDEX IF NOT EXISTS ctl_produtos_marca_idx
  ON dt_catalogo.ctl_produtos (marca) WHERE ativo;
CREATE UNIQUE INDEX IF NOT EXISTS ctl_produtos_codigo_uk
  ON dt_catalogo.ctl_produtos (codigo_interno)
  WHERE codigo_interno IS NOT NULL;
CREATE INDEX IF NOT EXISTS ctl_custos_subtipo_idx
  ON dt_catalogo.ctl_custos (tipo_custo, subtipo) WHERE ativo;
CREATE INDEX IF NOT EXISTS ctl_custos_marca_idx
  ON dt_catalogo.ctl_custos (marca) WHERE ativo;
CREATE INDEX IF NOT EXISTS ctl_custos_fornecedor_idx
  ON dt_catalogo.ctl_custos (id_fornecedor) WHERE ativo;
CREATE UNIQUE INDEX IF NOT EXISTS ctl_custos_codigo_uk
  ON dt_catalogo.ctl_custos (codigo_interno)
  WHERE codigo_interno IS NOT NULL;

-- —— Views BI ——

CREATE OR REPLACE VIEW dt_catalogo.vw_bi_produtos AS
SELECT
  p.id_produto,
  p.codigo_interno,
  p.linha,
  l.nome AS linha_nome,
  l.tipo_sistema,
  p.produto AS modelo,
  p.familia,
  f.nome AS familia_nome,
  f.segmento AS segmento_familia,
  COALESCE(p.segmento, f.segmento) AS segmento,
  p.cor,
  c.familia_cor,
  p.acabamento,
  p.marca,
  p.categoria,
  cat.nome AS categoria_nome,
  p.descricao,
  p.unidade_venda,
  p.ativo,
  p.criado_em,
  p.alterado_em
FROM dt_catalogo.ctl_produtos p
LEFT JOIN dt_catalogo.dim_linha l ON l.codigo = p.linha
LEFT JOIN dt_catalogo.dim_familia_produto f ON f.codigo = p.familia
LEFT JOIN dt_catalogo.dim_cor c ON c.codigo = p.cor
LEFT JOIN dt_catalogo.dim_categoria_produto cat ON cat.codigo = p.categoria;

CREATE OR REPLACE VIEW dt_catalogo.vw_bi_custos AS
SELECT
  cu.id_custo,
  cu.codigo_interno,
  cu.tipo_custo,
  tc.nome AS tipo_custo_nome,
  tc.grupo_bi,
  cu.subtipo,
  cu.descricao,
  cu.linha,
  cu.produto AS modelo_ref,
  cu.cor,
  cu.espessura,
  e.mm AS espessura_mm,
  cu.tipo_vidro,
  tv.familia AS familia_vidro,
  cu.marca,
  cu.acabamento,
  cu.unidade_custo,
  cu.origem,
  cu.id_produto,
  cu.id_fornecedor,
  fo.nome AS fornecedor_nome,
  fo.uf AS fornecedor_uf,
  cu.ativo,
  cu.criado_em,
  cu.alterado_em
FROM dt_catalogo.ctl_custos cu
LEFT JOIN dt_catalogo.dim_tipo_custo tc ON tc.codigo = cu.tipo_custo
LEFT JOIN dt_catalogo.dim_espessura e ON e.codigo = cu.espessura
LEFT JOIN dt_catalogo.dim_tipo_vidro tv ON tv.codigo = cu.tipo_vidro
LEFT JOIN dt_catalogo.dim_fornecedor fo ON fo.id_fornecedor = cu.id_fornecedor;

COMMENT ON VIEW dt_catalogo.vw_bi_produtos IS
  'Camada BI do catálogo comercial — dimensões para Power BI / rentabilidade.';
COMMENT ON VIEW dt_catalogo.vw_bi_custos IS
  'Camada BI do catálogo de custos — gasto por tipo, marca, espessura, fornecedor.';
