-- Seeds do catálogo: combinações reais de mercado (vidraçaria / esquadrias).
-- IDs explícitos para preservar a relação ctl_custos.id_produto -> ctl_produtos.

INSERT INTO dt_catalogo.ctl_produtos
  (id_produto, linha, produto, cor, categoria, descricao, unidade_venda, ativo)
VALUES
-- ===== LINHA GOLD (32mm - alto padrão / vãos amplos) =====
(1,  'GOLD', 'JANELA',            'BRANCO',           'ESQUADRIA', 'Janela linha Gold branco', 'UN', TRUE),
(2,  'GOLD', 'JANELA',            'PRETO',            'ESQUADRIA', 'Janela linha Gold preto', 'UN', TRUE),
(3,  'GOLD', 'JANELA',            'BRONZE',           'ESQUADRIA', 'Janela linha Gold bronze', 'UN', TRUE),
(4,  'GOLD', 'JANELA',            'CHAMPAGNE',        'ESQUADRIA', 'Janela linha Gold champagne', 'UN', TRUE),
(5,  'GOLD', 'JANELA DE CORRER',  'BRANCO',           'ESQUADRIA', 'Janela de correr Gold branco', 'UN', TRUE),
(6,  'GOLD', 'JANELA DE CORRER',  'PRETO',            'ESQUADRIA', 'Janela de correr Gold preto', 'UN', TRUE),
(7,  'GOLD', 'MAXIMAR',           'BRANCO',           'ESQUADRIA', 'Maxim-ar Gold branco', 'UN', TRUE),
(8,  'GOLD', 'MAXIMAR',           'PRETO',            'ESQUADRIA', 'Maxim-ar Gold preto', 'UN', TRUE),
(9,  'GOLD', 'MAXIMAR',           'BRONZE',           'ESQUADRIA', 'Maxim-ar Gold bronze', 'UN', TRUE),
(10, 'GOLD', 'PORTA',             'BRANCO',           'ESQUADRIA', 'Porta Gold branco', 'UN', TRUE),
(11, 'GOLD', 'PORTA',             'PRETO',            'ESQUADRIA', 'Porta Gold preto', 'UN', TRUE),
(12, 'GOLD', 'PORTA DE CORRER',   'BRANCO',           'ESQUADRIA', 'Porta de correr Gold branco', 'UN', TRUE),
(13, 'GOLD', 'PORTA DE CORRER',   'PRETO',            'ESQUADRIA', 'Porta de correr Gold preto', 'UN', TRUE),
(14, 'GOLD', 'PORTA DE CORRER',   'NATURAL/ALUMÍNIO', 'ESQUADRIA', 'Porta de correr Gold natural', 'UN', TRUE),
(15, 'GOLD', 'PORTA DE GIRO',     'PRETO',            'ESQUADRIA', 'Porta de giro Gold preto', 'UN', TRUE),
(16, 'GOLD', 'PORTA BALCÃO',      'PRETO',            'ESQUADRIA', 'Porta balcão Gold preto', 'UN', TRUE),
(17, 'GOLD', 'PORTA PIVOTANTE',   'PRETO',            'ESQUADRIA', 'Porta pivotante Gold preto', 'UN', TRUE),
(18, 'GOLD', 'VENEZIANA',         'BRANCO',           'ESQUADRIA', 'Veneziana Gold branco', 'UN', TRUE),
-- ===== LINHA SUPREMA (25mm - médio padrão / custo-benefício) =====
(19, 'SUPREMA', 'JANELA',           'BRANCO',    'ESQUADRIA', 'Janela Suprema branco', 'UN', TRUE),
(20, 'SUPREMA', 'JANELA',           'PRETO',     'ESQUADRIA', 'Janela Suprema preto', 'UN', TRUE),
(21, 'SUPREMA', 'JANELA',           'VERDE',     'ESQUADRIA', 'Janela Suprema verde', 'UN', TRUE),
(22, 'SUPREMA', 'JANELA',           'BRONZE',    'ESQUADRIA', 'Janela Suprema bronze', 'UN', TRUE),
(23, 'SUPREMA', 'JANELA DE CORRER', 'BRANCO',    'ESQUADRIA', 'Janela de correr Suprema branco', 'UN', TRUE),
(24, 'SUPREMA', 'JANELA DE CORRER', 'PRETO',     'ESQUADRIA', 'Janela de correr Suprema preto', 'UN', TRUE),
(25, 'SUPREMA', 'MAXIMAR',          'BRANCO',    'ESQUADRIA', 'Maxim-ar Suprema branco', 'UN', TRUE),
(26, 'SUPREMA', 'MAXIMAR',          'PRETO',     'ESQUADRIA', 'Maxim-ar Suprema preto', 'UN', TRUE),
(27, 'SUPREMA', 'MAXIMAR',          'VERDE',     'ESQUADRIA', 'Maxim-ar Suprema verde', 'UN', TRUE),
(28, 'SUPREMA', 'PORTA',            'BRANCO',    'ESQUADRIA', 'Porta Suprema branco', 'UN', TRUE),
(29, 'SUPREMA', 'PORTA',            'PRETO',     'ESQUADRIA', 'Porta Suprema preto', 'UN', TRUE),
(30, 'SUPREMA', 'PORTA DE CORRER',  'BRANCO',    'ESQUADRIA', 'Porta de correr Suprema branco', 'UN', TRUE),
(31, 'SUPREMA', 'PORTA DE CORRER',  'PRETO',     'ESQUADRIA', 'Porta de correr Suprema preto', 'UN', TRUE),
(32, 'SUPREMA', 'PORTA DE GIRO',    'BRANCO',    'ESQUADRIA', 'Porta de giro Suprema branco', 'UN', TRUE),
(33, 'SUPREMA', 'PORTA CAMARÃO',    'PRETO',     'ESQUADRIA', 'Porta camarão Suprema preto', 'UN', TRUE),
(34, 'SUPREMA', 'JANELA TOMBANTE',  'BRANCO',    'ESQUADRIA', 'Janela tombante Suprema branco', 'UN', TRUE),
(35, 'SUPREMA', 'JANELA BASCULANTE','BRANCO',    'ESQUADRIA', 'Janela basculante Suprema branco', 'UN', TRUE),
-- ===== LINHA MASTER =====
(36, 'MASTER', 'JANELA',          'BRANCO', 'ESQUADRIA', 'Janela Master branco', 'UN', TRUE),
(37, 'MASTER', 'JANELA',          'PRETO',  'ESQUADRIA', 'Janela Master preto', 'UN', TRUE),
(38, 'MASTER', 'PORTA DE CORRER', 'PRETO',  'ESQUADRIA', 'Porta de correr Master preto', 'UN', TRUE),
(39, 'MASTER', 'MAXIMAR',         'BRONZE', 'ESQUADRIA', 'Maxim-ar Master bronze', 'UN', TRUE),
(40, 'MASTER', 'PORTA DE GIRO',   'PRETO',  'ESQUADRIA', 'Porta de giro Master preto', 'UN', TRUE),
-- ===== LINHAS NUMÉRICAS (sistemas clássicos de perfil) =====
(41, '25', 'JANELA',          'BRANCO',           'ESQUADRIA', 'Janela linha 25 branco', 'UN', TRUE),
(42, '25', 'JANELA',          'NATURAL/ALUMÍNIO', 'ESQUADRIA', 'Janela linha 25 natural', 'UN', TRUE),
(43, '25', 'PORTA',           'BRANCO',           'ESQUADRIA', 'Porta linha 25 branco', 'UN', TRUE),
(44, '25', 'MAXIMAR',         'BRANCO',           'ESQUADRIA', 'Maxim-ar linha 25 branco', 'UN', TRUE),
(45, '30', 'JANELA',          'BRANCO',           'ESQUADRIA', 'Janela linha 30 branco', 'UN', TRUE),
(46, '30', 'PORTA DE CORRER', 'PRETO',            'ESQUADRIA', 'Porta de correr linha 30 preto', 'UN', TRUE),
(47, '42', 'JANELA',          'BRANCO',           'ESQUADRIA', 'Janela linha 42 branco', 'UN', TRUE),
(48, '42', 'PORTA DE CORRER', 'PRETO',            'ESQUADRIA', 'Porta de correr linha 42 preto', 'UN', TRUE),
(49, '42', 'PORTA BALCÃO',    'PRETO',            'ESQUADRIA', 'Porta balcão linha 42 preto', 'UN', TRUE),
(50, '50', 'JANELA',          'PRETO',            'ESQUADRIA', 'Janela linha 50 preto', 'UN', TRUE),
(51, '50', 'PORTA DE CORRER', 'PRETO',            'ESQUADRIA', 'Porta de correr linha 50 preto', 'UN', TRUE),
(52, '50', 'PORTA PIVOTANTE', 'PRETO',            'ESQUADRIA', 'Porta pivotante linha 50 preto', 'UN', TRUE),
-- ===== INFINITY / MINIMALISTA (vão amplo, perfil fino) =====
(53, 'INFINITY',    'PORTA DE CORRER', 'PRETO',            'ESQUADRIA', 'Porta de correr Infinity preto', 'UN', TRUE),
(54, 'INFINITY',    'PORTA DE CORRER', 'NATURAL/ALUMÍNIO', 'ESQUADRIA', 'Porta de correr Infinity natural', 'UN', TRUE),
(55, 'INFINITY',    'JANELA DE CORRER','PRETO',            'ESQUADRIA', 'Janela de correr Infinity preto', 'UN', TRUE),
(56, 'MINIMALISTA', 'PORTA DE CORRER', 'PRETO',            'ESQUADRIA', 'Porta de correr Minimalista preto', 'UN', TRUE),
(57, 'MINIMALISTA', 'PORTA DE CORRER', 'PRETO FOSCO',      'ESQUADRIA', 'Porta de correr Minimalista preto fosco', 'UN', TRUE),
(58, 'MINIMALISTA', 'PORTA PIVOTANTE', 'PRETO',            'ESQUADRIA', 'Porta pivotante Minimalista preto', 'UN', TRUE),
(59, 'MINIMALISTA', 'JANELA DE CORRER','GRAFITE',          'ESQUADRIA', 'Janela de correr Minimalista grafite', 'UN', TRUE),
-- ===== BOX (linha própria TEMPERADO/BOX) =====
(60, 'TEMPERADO', 'BOX',            'INCOLOR', 'BOX', 'Box temperado incolor', 'UN', TRUE),
(61, 'TEMPERADO', 'BOX',            'FUMÊ',    'BOX', 'Box temperado fumê', 'UN', TRUE),
(62, 'TEMPERADO', 'BOX',            'VERDE',   'BOX', 'Box temperado verde', 'UN', TRUE),
(63, 'TEMPERADO', 'BOX FRONTAL',    'INCOLOR', 'BOX', 'Box frontal temperado incolor', 'UN', TRUE),
(64, 'TEMPERADO', 'BOX FRONTAL',    'FUMÊ',    'BOX', 'Box frontal temperado fumê', 'UN', TRUE),
(65, 'TEMPERADO', 'BOX DE CANTO',   'INCOLOR', 'BOX', 'Box de canto temperado incolor', 'UN', TRUE),
(66, 'TEMPERADO', 'BOX ARTICULADO', 'INCOLOR', 'BOX', 'Box articulado temperado incolor', 'UN', TRUE),
(67, 'TEMPERADO', 'BOX ARTICULADO', 'FUMÊ',    'BOX', 'Box articulado temperado fumê', 'UN', TRUE),
-- ===== ESTRUTURAL / FACHADA / ARQUITETURA EM VIDRO =====
(68, 'FACHADA', 'FACHADA',       'INCOLOR',    'ESTRUTURAL',   'Fachada de vidro incolor', 'M2', TRUE),
(69, 'FACHADA', 'FACHADA',       'FUMÊ',       'ESTRUTURAL',   'Fachada de vidro fumê', 'M2', TRUE),
(70, 'FACHADA', 'PELE DE VIDRO', 'INCOLOR',    'ESTRUTURAL',   'Pele de vidro incolor', 'M2', TRUE),
(71, 'FACHADA', 'PELE DE VIDRO', 'VERDE',      'ESTRUTURAL',   'Pele de vidro verde', 'M2', TRUE),
(72, 'FACHADA', 'GUARDA-CORPO',  'INCOLOR',    'ESTRUTURAL',   'Guarda-corpo de vidro incolor', 'ML', TRUE),
(73, 'FACHADA', 'GUARDA-CORPO',  'FUMÊ',       'ESTRUTURAL',   'Guarda-corpo de vidro fumê', 'ML', TRUE),
(74, 'FACHADA', 'GUARDA-CORPO',  'AÇO CORTEN', 'ESTRUTURAL',   'Guarda-corpo com acabamento aço corten', 'ML', TRUE),
(75, 'FACHADA', 'DIVISÓRIA',     'INCOLOR',    'ESTRUTURAL',   'Divisória de vidro incolor', 'M2', TRUE),
(76, 'FACHADA', 'DIVISÓRIA',     'FUMÊ',       'ESTRUTURAL',   'Divisória de vidro fumê', 'M2', TRUE),
(77, 'FACHADA', 'COBERTURA',     'INCOLOR',    'ESTRUTURAL',   'Cobertura de vidro incolor', 'M2', TRUE),
(78, 'FACHADA', 'CLARABÓIA',     'INCOLOR',    'ESTRUTURAL',   'Clarabóia de vidro incolor', 'UN', TRUE),
(79, 'FACHADA', 'ESPELHO',       'PRATA',      'VIDRO_AVULSO', 'Espelho prata', 'M2', TRUE),
(80, 'FACHADA', 'ESPELHO',       'BRONZE',     'VIDRO_AVULSO', 'Espelho bronze', 'M2', TRUE),
(81, 'FACHADA', 'TAMPO',         'INCOLOR',    'VIDRO_AVULSO', 'Tampo de vidro temperado', 'M2', TRUE),
(82, 'FACHADA', 'PRATELEIRA',    'INCOLOR',    'VIDRO_AVULSO', 'Prateleira de vidro temperado', 'UN', TRUE),
-- ===== CORES ADICIONAIS EM LINHAS POPULARES =====
(83, 'GOLD',     'JANELA',          'MARROM',       'ESQUADRIA', 'Janela Gold marrom', 'UN', TRUE),
(84, 'GOLD',     'PORTA DE CORRER', 'GRAFITE',      'ESQUADRIA', 'Porta de correr Gold grafite', 'UN', TRUE),
(85, 'SUPREMA',  'JANELA',          'FUMÊ',         'ESQUADRIA', 'Janela Suprema fumê (perfil)', 'UN', TRUE),
(86, 'SUPREMA',  'PORTA',           'CHAMPAGNE',    'ESQUADRIA', 'Porta Suprema champagne', 'UN', TRUE),
(87, 'GOLD',     'JANELA',          'AÇO CORTEN',   'ESQUADRIA', 'Janela Gold aço corten', 'UN', TRUE),
(88, 'INFINITY', 'PORTA DE CORRER', 'BRANCO FOSCO', 'ESQUADRIA', 'Porta de correr Infinity branco fosco', 'UN', TRUE);

INSERT INTO dt_catalogo.ctl_custos
  (id_custo, id_produto, tipo_custo, descricao, linha, produto, cor, espessura, tipo_vidro, unidade_custo, ativo)
VALUES
-- ===== VIDROS POR ESPESSURA (sem linha - custo genérico) =====
(1,  NULL, 'VIDRO', 'Vidro float 3mm incolor',           NULL, NULL, 'INCOLOR', '3MM',  'FLOAT',       'M2', TRUE),
(2,  NULL, 'VIDRO', 'Vidro float 4mm incolor',           NULL, NULL, 'INCOLOR', '4MM',  'FLOAT',       'M2', TRUE),
(3,  NULL, 'VIDRO', 'Vidro float 5mm incolor',           NULL, NULL, 'INCOLOR', '5MM',  'FLOAT',       'M2', TRUE),
(4,  NULL, 'VIDRO', 'Vidro temperado 6mm incolor',       NULL, NULL, 'INCOLOR', '6MM',  'TEMPERADO',   'M2', TRUE),
(5,  NULL, 'VIDRO', 'Vidro temperado 8mm incolor',       NULL, NULL, 'INCOLOR', '8MM',  'TEMPERADO',   'M2', TRUE),
(6,  NULL, 'VIDRO', 'Vidro temperado 10mm incolor',      NULL, NULL, 'INCOLOR', '10MM', 'TEMPERADO',   'M2', TRUE),
(7,  NULL, 'VIDRO', 'Vidro temperado 12mm incolor',      NULL, NULL, 'INCOLOR', '12MM', 'TEMPERADO',   'M2', TRUE),
(8,  NULL, 'VIDRO', 'Vidro temperado 15mm incolor',      NULL, NULL, 'INCOLOR', '15MM', 'TEMPERADO',   'M2', TRUE),
(9,  NULL, 'VIDRO', 'Vidro temperado 19mm incolor',      NULL, NULL, 'INCOLOR', '19MM', 'TEMPERADO',   'M2', TRUE),
(10, NULL, 'VIDRO', 'Vidro temperado 8mm fumê',          NULL, NULL, 'FUMÊ',    '8MM',  'TEMPERADO',   'M2', TRUE),
(11, NULL, 'VIDRO', 'Vidro temperado 8mm verde',         NULL, NULL, 'VERDE',   '8MM',  'TEMPERADO',   'M2', TRUE),
(12, NULL, 'VIDRO', 'Vidro temperado 10mm fumê',         NULL, NULL, 'FUMÊ',    '10MM', 'TEMPERADO',   'M2', TRUE),
(13, NULL, 'VIDRO', 'Vidro laminado 8mm (4+4) incolor',  NULL, NULL, 'INCOLOR', '8MM',  'LAMINADO',    'M2', TRUE),
(14, NULL, 'VIDRO', 'Vidro laminado 10mm (5+5) incolor', NULL, NULL, 'INCOLOR', '10MM', 'LAMINADO',    'M2', TRUE),
(15, NULL, 'VIDRO', 'Vidro serigrafado 8mm',             NULL, NULL, 'BRANCO',  '8MM',  'SERIGRAFADO', 'M2', TRUE),
-- ===== PERFIS POR LINHA + COR (sem produto específico) =====
(16, NULL, 'PERFIL', 'Perfil linha GOLD branco',             'GOLD',        NULL, 'BRANCO',           '32MM', NULL, 'ML', TRUE),
(17, NULL, 'PERFIL', 'Perfil linha GOLD preto',              'GOLD',        NULL, 'PRETO',            '32MM', NULL, 'ML', TRUE),
(18, NULL, 'PERFIL', 'Perfil linha GOLD bronze',             'GOLD',        NULL, 'BRONZE',           '32MM', NULL, 'ML', TRUE),
(19, NULL, 'PERFIL', 'Perfil linha GOLD champagne',          'GOLD',        NULL, 'CHAMPAGNE',        '32MM', NULL, 'ML', TRUE),
(20, NULL, 'PERFIL', 'Perfil linha GOLD natural/alumínio',   'GOLD',        NULL, 'NATURAL/ALUMÍNIO', '32MM', NULL, 'ML', TRUE),
(21, NULL, 'PERFIL', 'Perfil linha SUPREMA branco',          'SUPREMA',     NULL, 'BRANCO',           '25MM', NULL, 'ML', TRUE),
(22, NULL, 'PERFIL', 'Perfil linha SUPREMA preto',           'SUPREMA',     NULL, 'PRETO',            '25MM', NULL, 'ML', TRUE),
(23, NULL, 'PERFIL', 'Perfil linha SUPREMA verde',           'SUPREMA',     NULL, 'VERDE',            '25MM', NULL, 'ML', TRUE),
(24, NULL, 'PERFIL', 'Perfil linha SUPREMA bronze',          'SUPREMA',     NULL, 'BRONZE',           '25MM', NULL, 'ML', TRUE),
(25, NULL, 'PERFIL', 'Perfil linha 25 branco',               '25',          NULL, 'BRANCO',           '25MM', NULL, 'ML', TRUE),
(26, NULL, 'PERFIL', 'Perfil linha 42 preto',                '42',          NULL, 'PRETO',            '42MM', NULL, 'ML', TRUE),
(27, NULL, 'PERFIL', 'Perfil linha 50 preto',                '50',          NULL, 'PRETO',            '50MM', NULL, 'ML', TRUE),
(28, NULL, 'PERFIL', 'Perfil linha INFINITY preto',          'INFINITY',    NULL, 'PRETO',            NULL,   NULL, 'ML', TRUE),
(29, NULL, 'PERFIL', 'Perfil linha MINIMALISTA preto fosco', 'MINIMALISTA', NULL, 'PRETO FOSCO',      NULL,   NULL, 'ML', TRUE),
-- ===== FERRAGENS / ACESSÓRIOS / CONSUMÍVEIS / SERVIÇOS =====
(30, NULL, 'FERRAGEM',   'Roldana para porta de correr',      NULL,        'PORTA DE CORRER', NULL,      NULL,   NULL, 'UN', TRUE),
(31, NULL, 'FERRAGEM',   'Fecho maxim-ar',                    NULL,        'MAXIMAR',         NULL,      NULL,   NULL, 'UN', TRUE),
(32, NULL, 'FERRAGEM',   'Dobradiça porta de giro',           NULL,        'PORTA DE GIRO',   NULL,      NULL,   NULL, 'UN', TRUE),
(33, NULL, 'FERRAGEM',   'Pivô para porta pivotante',         NULL,        'PORTA PIVOTANTE', NULL,      NULL,   NULL, 'UN', TRUE),
(34, NULL, 'ACESSORIO',  'Puxador alumínio preto',            NULL,        NULL,              'PRETO',   NULL,   NULL, 'UN', TRUE),
(35, NULL, 'ACESSORIO',  'Kit box frontal temperado',         'TEMPERADO', 'BOX FRONTAL',     NULL,      NULL,   NULL, 'UN', TRUE),
(36, NULL, 'ACESSORIO',  'Kit box articulado',                'TEMPERADO', 'BOX ARTICULADO',  NULL,      NULL,   NULL, 'UN', TRUE),
(37, NULL, 'ACESSORIO',  'Trilho superior Gold',              'GOLD',      'PORTA DE CORRER', NULL,      '32MM', NULL, 'ML', TRUE),
(38, NULL, 'ACESSORIO',  'Trilho inferior Suprema',           'SUPREMA',   'PORTA DE CORRER', NULL,      '25MM', NULL, 'ML', TRUE),
(39, NULL, 'SILICONE',   'Silicone neutro transparente',      NULL,        NULL,              'INCOLOR', NULL,   NULL, 'UN', TRUE),
(40, NULL, 'SILICONE',   'Silicone neutro preto',             NULL,        NULL,              'PRETO',   NULL,   NULL, 'UN', TRUE),
(41, NULL, 'CONSUMIVEL', 'Fita dupla face estrutural',        NULL,        NULL,              NULL,      NULL,   NULL, 'ML', TRUE),
(42, NULL, 'CONSUMIVEL', 'Disco de corte diamantado',         NULL,        NULL,              NULL,      NULL,   NULL, 'UN', TRUE),
(43, NULL, 'SERVICO',    'Mão de obra instalação esquadria',  NULL,        NULL,              NULL,      NULL,   NULL, 'UN', TRUE),
(44, NULL, 'SERVICO',    'Temperagem de vidro',               NULL,        NULL,              NULL,      NULL,   NULL, 'M2', TRUE),
-- ===== CUSTOS LIGADOS A SKU COMERCIAL (id_produto preenchido) =====
(45, 12, 'PERFIL', 'Composição perfil - Porta de correr Gold preto',      'GOLD',      'PORTA DE CORRER', 'PRETO',   '32MM', NULL,        'ML', TRUE),
(46, 13, 'PERFIL', 'Composição perfil - Porta de correr Gold preto (alt)','GOLD',      'PORTA DE CORRER', 'PRETO',   '32MM', NULL,        'ML', TRUE),
(47, 30, 'PERFIL', 'Composição perfil - Porta de correr Suprema branco',  'SUPREMA',   'PORTA DE CORRER', 'BRANCO',  '25MM', NULL,        'ML', TRUE),
(48, 63, 'VIDRO',  'Vidro box frontal 8mm incolor',                       'TEMPERADO', 'BOX FRONTAL',     'INCOLOR', '8MM',  'TEMPERADO', 'M2', TRUE),
(49, 64, 'VIDRO',  'Vidro box frontal 8mm fumê',                          'TEMPERADO', 'BOX FRONTAL',     'FUMÊ',    '8MM',  'TEMPERADO', 'M2', TRUE),
(50, 72, 'VIDRO',  'Vidro guarda-corpo 12mm incolor',                     'FACHADA',   'GUARDA-CORPO',    'INCOLOR', '12MM', 'TEMPERADO', 'M2', TRUE);

-- IDs vieram explícitos no seed: avança as sequences para o próximo valor livre.
SELECT setval(pg_get_serial_sequence('dt_catalogo.ctl_produtos', 'id_produto'), (SELECT max(id_produto) FROM dt_catalogo.ctl_produtos));
SELECT setval(pg_get_serial_sequence('dt_catalogo.ctl_custos', 'id_custo'), (SELECT max(id_custo) FROM dt_catalogo.ctl_custos));
