-- =============================================================================
-- Catálogo comercial e de custos. Porte de whglazia.dt_catalogo.
-- ctl_produtos = o que se VENDE | ctl_custos = o que se COMPRA
-- A regra "GOLD não oferece BOX" continua garantida pelas combinações
-- existentes em ctl_produtos, não por tabelas de linha/tipo separadas.
-- =============================================================================

CREATE TABLE dt_catalogo.ctl_produtos (
  id_produto    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  linha         text NOT NULL,
  produto       text NOT NULL,
  cor           text NOT NULL,
  categoria     text NOT NULL,
  descricao     text,
  unidade_venda text NOT NULL DEFAULT 'UN',
  ativo         boolean NOT NULL DEFAULT true,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  alterado_em   timestamptz,
  CONSTRAINT ctl_produtos_combinacao_uk UNIQUE (linha, produto, cor),
  CONSTRAINT ctl_produtos_unidade_chk CHECK (unidade_venda IN ('UN', 'M2', 'ML', 'KG', 'L'))
);
COMMENT ON TABLE dt_catalogo.ctl_produtos IS 'Catálogo comercial. Base do dropdown de vendas: linha -> produtos válidos -> cores válidas.';
COMMENT ON COLUMN dt_catalogo.ctl_produtos.linha IS 'Linha comercial do perfil/sistema. Ex.: GOLD, SUPREMA, TEMPERADO, FACHADA.';
COMMENT ON COLUMN dt_catalogo.ctl_produtos.produto IS 'Tipo do item final vendido. Ex.: JANELA, PORTA DE CORRER, BOX FRONTAL.';
COMMENT ON COLUMN dt_catalogo.ctl_produtos.cor IS 'Acabamento/cor do perfil ou vidro. Ex.: BRANCO, PRETO, FUMÊ.';
COMMENT ON COLUMN dt_catalogo.ctl_produtos.categoria IS 'Agrupamento para filtros do CRM. Ex.: ESQUADRIA, BOX, ESTRUTURAL, VIDRO_AVULSO.';
COMMENT ON COLUMN dt_catalogo.ctl_produtos.ativo IS 'FALSE = oculto no menu suspenso sem apagar histórico.';
CREATE INDEX ctl_produtos_linha_idx ON dt_catalogo.ctl_produtos (linha, produto, cor) WHERE ativo;

CREATE TABLE dt_catalogo.ctl_custos (
  id_custo      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto    integer REFERENCES dt_catalogo.ctl_produtos(id_produto) ON UPDATE CASCADE ON DELETE SET NULL,
  tipo_custo    text NOT NULL,
  descricao     text NOT NULL,
  linha         text,
  produto       text,
  cor           text,
  espessura     text,
  tipo_vidro    text,
  unidade_custo text NOT NULL DEFAULT 'UN',
  ativo         boolean NOT NULL DEFAULT true,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  alterado_em   timestamptz,
  CONSTRAINT ctl_custos_unidade_chk CHECK (unidade_custo IN ('UN', 'M2', 'ML', 'KG', 'L')),
  CONSTRAINT ctl_custos_vidro_chk CHECK (tipo_vidro IS NULL OR tipo_custo = 'VIDRO')
);
COMMENT ON TABLE dt_catalogo.ctl_custos IS 'Catálogo de custos/insumos. Liga-se a ctl_produtos via id_produto (opcional) ou via linha/produto/cor/espessura.';
COMMENT ON COLUMN dt_catalogo.ctl_custos.id_produto IS 'Preenchido quando o custo for específico de um SKU comercial.';
COMMENT ON COLUMN dt_catalogo.ctl_custos.tipo_custo IS 'Classificação do insumo. Ex.: VIDRO, PERFIL, FERRAGEM, ACESSORIO, SILICONE, SERVICO, CONSUMIVEL.';
COMMENT ON COLUMN dt_catalogo.ctl_custos.tipo_vidro IS 'Só quando tipo_custo = VIDRO. Ex.: FLOAT, TEMPERADO, LAMINADO, SERIGRAFADO.';
CREATE INDEX ctl_custos_tipo_idx ON dt_catalogo.ctl_custos (tipo_custo, linha, espessura) WHERE ativo;
CREATE INDEX ctl_custos_produto_idx ON dt_catalogo.ctl_custos (id_produto);
